package com.reelvault.model;

import io.hypersistence.utils.hibernate.type.array.StringArrayType;
import jakarta.persistence.*;
import org.hibernate.annotations.Type;

import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * JPA entity mapping to the `knowledge_items` table in Supabase PostgreSQL.
 *
 * <p>Key type-mapping notes:
 * <ul>
 *   <li>{@code tags} — PostgreSQL {@code TEXT[]} mapped via hypersistence-utils
 *       {@link StringArrayType} for proper array handling.</li>
 *   <li>{@code embedding} — PostgreSQL {@code vector(384)} stored as a String in
 *       the format {@code "[f1,f2,...,f384]"}. PostgreSQL auto-casts the text literal
 *       to the vector type on insert/update, and returns the text representation
 *       on select via {@code ResultSet.getString()}.</li>
 * </ul>
 */
@Entity
@Table(name = "knowledge_items")
public class KnowledgeItem {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(columnDefinition = "uuid", updatable = false, nullable = false)
    private UUID id;

    @Column(nullable = false)
    private String title;

    @Column(columnDefinition = "text")
    private String description;

    @Column(name = "original_url", columnDefinition = "text")
    private String originalUrl;

    @Column(name = "source_url", columnDefinition = "text")
    private String sourceUrl;

    @Column(name = "content_type")
    private String contentType;

    /**
     * Tags stored as a PostgreSQL TEXT[] array.
     * hypersistence-utils StringArrayType handles the JDBC Array mapping.
     */
    @Type(StringArrayType.class)
    @Column(
        name = "tags",
        columnDefinition = "text[]"
    )
    private String[] tags;

    @Column(name = "personal_notes", columnDefinition = "text")
    private String personalNotes;

    /**
     * 384-dimensional embedding from sentence-transformers/all-MiniLM-L6-v2.
     * Stored as PostgreSQL vector(384). The String field holds the text
     * representation "[f1,f2,...,f384]" which PostgreSQL casts to vector.
     */
    @Column(columnDefinition = "vector(384)")
    private String embedding;

    @Column(name = "created_at")
    private OffsetDateTime createdAt;

    @Column(name = "updated_at")
    private OffsetDateTime updatedAt;

    // ----------------------------------------------------------------
    // Lifecycle callbacks
    // ----------------------------------------------------------------

    @PrePersist
    protected void onCreate() {
        OffsetDateTime now = OffsetDateTime.now();
        this.createdAt = now;
        this.updatedAt = now;
    }

    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = OffsetDateTime.now();
    }

    // ----------------------------------------------------------------
    // Getters & Setters
    // ----------------------------------------------------------------

    public UUID getId() { return id; }
    // No setId() — ID is generated by the database and must not be set externally (@GeneratedValue)

    public String getTitle() { return title; }
    public void setTitle(String title) { this.title = title; }

    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }

    public String getOriginalUrl() { return originalUrl; }
    public void setOriginalUrl(String originalUrl) { this.originalUrl = originalUrl; }

    public String getSourceUrl() { return sourceUrl; }
    public void setSourceUrl(String sourceUrl) { this.sourceUrl = sourceUrl; }

    public String getContentType() { return contentType; }
    public void setContentType(String contentType) { this.contentType = contentType; }

    public String[] getTags() { return tags; }
    public void setTags(String[] tags) { this.tags = tags; }

    public String getPersonalNotes() { return personalNotes; }
    public void setPersonalNotes(String personalNotes) { this.personalNotes = personalNotes; }

    public String getEmbedding() { return embedding; }
    public void setEmbedding(String embedding) { this.embedding = embedding; }

    public OffsetDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(OffsetDateTime createdAt) { this.createdAt = createdAt; }

    public OffsetDateTime getUpdatedAt() { return updatedAt; }
    public void setUpdatedAt(OffsetDateTime updatedAt) { this.updatedAt = updatedAt; }
}
